apiVersion: v1
kind: Service
metadata:
  name: kitchen
  labels:
    app: kitchen
  namespace: tech-challenge
spec:
  selector:
    app: kitchen
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080